### ISSUE TITLE
Uncaught TypeError: _this.notificationEl.querySelector is not a function

### ISSUE THREAD

**Issue by DotNetRussell** [ionide/ionide-atom-installer#21]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.4 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [ionide-installer](https://github.com/Ionide/ionide-installer) package 1.4.0

### Stack Trace

Uncaught TypeError: _this.notificationEl.querySelector is not a function

```
At C:\Users\Anthony\.atom\packages\ionide-installer\node_modules\atom-package-deps\lib\view.js:22

TypeError: _this.notificationEl.querySelector is not a function
  at /packages/ionide-installer/node_modules/atom-package-deps/lib/view.js:36:62

```

### Commands

```
```

### Non-Core Packages

```
ionide-fake 1.2.2 
ionide-fsharp 1.9.3 
ionide-fsi 2.1.3 
ionide-installer 1.4.0 
ionide-paket 2.2.6 
language-fs-ionide 1.0.0 
```

**Comment by Yoshi325** [comment]
Looks like it's once again time to update "atom-package-deps".

https://github.com/ricardofbarros/linter-js-standard/issues/187

https://github.com/ricardofbarros/linter-js-standard/pull/193

https://github.com/hebaishi/linter-gcc/issues/126

https://github.com/spark/particle-dev/issues/210

https://github.com/hebaishi/linter-gcc/pull/137
